// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "API documentation untuk Backend MBG application.\n\n**Sistem Login:**\n- Admin: admin@email.com / password123\n- Kasir: kasir@email.com / password123\n- Driver: driver@email.com / password123\n\n**Authentication:**\n- Semua endpoint (kecuali login) memerlukan Bearer Token\n- Token didapat dari endpoint /auth/login\n- Format: Authorization: Bearer {token}\n\n**Role Permissions:**\n- Admin: Akses penuh ke semua fitur\n- Kasir: CRUD produk, pelanggan, pembayaran, lihat riwayat\n- Driver: Lihat pembayaran assigned, update status selesai, cetak surat jalan",
        "title": "Backend MBG API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:5000",
    "basePath": "/",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login user dengan email dan password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": {
                                    "type": "string",
                                    "format": "email",
                                    "example": "admin@email.com"
                                },
                                "password": {
                                    "type": "string",
                                    "example": "password123"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login berhasil",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"},
                                "token": {"type": "string"},
                                "user": {"$ref": "#/definitions/models.User"}
                            }
                        }
                    },
                    "400": {
                        "description": "Request tidak valid",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {"type": "string"}
                            }
                        }
                    },
                    "401": {
                        "description": "Email atau password salah",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/users/karyawan": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil semua data karyawan (admin only)",
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Get all karyawan",
                "responses": {
                    "200": {
                        "description": "Data karyawan berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.User"}
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Register karyawan baru (admin only)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Register karyawan baru",
                "parameters": [
                    {
                        "description": "Data karyawan baru",
                        "name": "karyawan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama", "email", "password", "role", "no_hp", "alamat"],
                            "properties": {
                                "nama": {
                                    "type": "string",
                                    "example": "driver2"
                                },
                                "email": {
                                    "type": "string",
                                    "format": "email",
                                    "example": "driver2@gmail.com"
                                },
                                "password": {
                                    "type": "string",
                                    "minLength": 6,
                                    "example": "password123"
                                },
                                "role": {
                                    "type": "string",
                                    "enum": ["admin", "kasir", "driver"],
                                    "example": "driver"
                                },
                                "no_hp": {
                                    "type": "string",
                                    "minLength": 10,
                                    "example": "083149869096"
                                },
                                "alamat": {
                                    "type": "string",
                                    "example": "Jln.rancabentang \\ rumah pak bombom"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Karyawan berhasil didaftarkan",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"},
                                "data": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/users/karyawan/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil data karyawan berdasarkan ID (admin only)",
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Get karyawan by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Karyawan ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data karyawan berhasil diambil",
                        "schema": {"$ref": "#/definitions/models.User"}
                    }
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Update data karyawan (admin only)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Update karyawan",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Karyawan ID"
                    },
                    {
                        "description": "Data karyawan yang akan diupdate",
                        "name": "karyawan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama", "email", "role", "no_hp", "alamat"],
                            "properties": {
                                "nama": {
                                    "type": "string",
                                    "example": "driver2 updated"
                                },
                                "email": {
                                    "type": "string",
                                    "format": "email",
                                    "example": "driver2.updated@gmail.com"
                                },
                                "role": {
                                    "type": "string",
                                    "enum": ["admin", "kasir", "driver"],
                                    "example": "driver"
                                },
                                "no_hp": {
                                    "type": "string",
                                    "minLength": 10,
                                    "example": "083149869096"
                                },
                                "alamat": {
                                    "type": "string",
                                    "example": "Jln.rancabentang \\ rumah pak bombom updated"
                                },
                                "password": {
                                    "type": "string",
                                    "description": "Optional - jika ingin mengubah password",
                                    "example": "newpassword123"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Karyawan berhasil diupdate",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Hapus karyawan (admin only)",
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Delete karyawan",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Karyawan ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Karyawan berhasil dihapus",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/users/karyawan/{id}/status": {
            "patch": {
                "security": [{"BearerAuth": []}],
                "description": "Update status karyawan aktif/nonaktif (admin only)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Karyawan"],
                "summary": "Update status karyawan",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Karyawan ID"
                    },
                    {
                        "description": "Status karyawan baru",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["status"],
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "enum": ["aktif", "nonaktif"],
                                    "example": "nonaktif",
                                    "description": "Status karyawan - aktif atau nonaktif"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status karyawan berhasil diupdate",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/produk": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil semua data produk",
                "produces": ["application/json"],
                "tags": ["Produk"],
                "summary": "Get all products",
                "responses": {
                    "200": {
                        "description": "Data produk berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Produk"}
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Menambahkan produk baru (admin/kasir)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Produk"],
                "summary": "Create new product",
                "parameters": [
                    {
                        "description": "Data produk baru",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama_produk", "kategori", "harga", "stok"],
                            "properties": {
                                "nama_produk": {
                                    "type": "string",
                                    "example": "Produk A"
                                },
                                "kategori": {
                                    "type": "string",
                                    "example": "Kategori 1"
                                },
                                "harga": {
                                    "type": "integer",
                                    "minimum": 1,
                                    "example": 50000
                                },
                                "stok": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "example": 100
                                },
                                "deskripsi": {
                                    "type": "string",
                                    "example": "Deskripsi produk"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Produk berhasil ditambahkan",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"},
                                "data": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/produk/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil data produk berdasarkan ID",
                "produces": ["application/json"],
                "tags": ["Produk"],
                "summary": "Get product by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Product ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data produk berhasil diambil",
                        "schema": {"$ref": "#/definitions/models.Produk"}
                    }
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Update data produk (admin/kasir)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Produk"],
                "summary": "Update product",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Product ID"
                    },
                    {
                        "description": "Data produk yang akan diupdate",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama_produk", "kategori", "harga", "stok"],
                            "properties": {
                                "nama_produk": {"type": "string"},
                                "kategori": {"type": "string"},
                                "harga": {"type": "integer", "minimum": 1},
                                "stok": {"type": "integer", "minimum": 0},
                                "deskripsi": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produk berhasil diupdate",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Hapus produk (admin/kasir)",
                "produces": ["application/json"],
                "tags": ["Produk"],
                "summary": "Delete product",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Product ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produk berhasil dihapus",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/pelanggan": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil semua data pelanggan",
                "produces": ["application/json"],
                "tags": ["Pelanggan"],
                "summary": "Get all customers",
                "responses": {
                    "200": {
                        "description": "Data pelanggan berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Pelanggan"}
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Menambahkan pelanggan baru (admin/kasir)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Pelanggan"],
                "summary": "Create new customer",
                "parameters": [
                    {
                        "description": "Data pelanggan baru",
                        "name": "pelanggan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama", "email", "no_hp", "alamat"],
                            "properties": {
                                "nama": {
                                    "type": "string",
                                    "example": "Jane Doe"
                                },
                                "email": {
                                    "type": "string",
                                    "format": "email",
                                    "example": "jane@email.com"
                                },
                                "no_hp": {
                                    "type": "string",
                                    "minLength": 10,
                                    "example": "08123456789"
                                },
                                "alamat": {
                                    "type": "string",
                                    "example": "Jl. Contoh No. 123"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pelanggan berhasil ditambahkan",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"},
                                "data": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/pelanggan/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil data pelanggan berdasarkan ID",
                "produces": ["application/json"],
                "tags": ["Pelanggan"],
                "summary": "Get customer by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Customer ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data pelanggan berhasil diambil",
                        "schema": {"$ref": "#/definitions/models.Pelanggan"}
                    }
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Update data pelanggan (admin/kasir)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Pelanggan"],
                "summary": "Update customer",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Customer ID"
                    },
                    {
                        "description": "Data pelanggan yang akan diupdate",
                        "name": "pelanggan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["nama", "email", "no_hp", "alamat"],
                            "properties": {
                                "nama": {"type": "string"},
                                "email": {"type": "string", "format": "email"},
                                "no_hp": {"type": "string", "minLength": 10},
                                "alamat": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pelanggan berhasil diupdate",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Hapus pelanggan (admin/kasir)",
                "produces": ["application/json"],
                "tags": ["Pelanggan"],
                "summary": "Delete customer",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Customer ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pelanggan berhasil dihapus",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/pembayaran": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil data pembayaran berdasarkan role user",
                "produces": ["application/json"],
                "tags": ["Pembayaran"],
                "summary": "Get payments by role",
                "responses": {
                    "200": {
                        "description": "Data pembayaran berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Pembayaran"}
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Membuat transaksi pembayaran baru (admin/kasir)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Pembayaran"],
                "summary": "Create new payment",
                "parameters": [
                    {
                        "description": "Data pembayaran baru",
                        "name": "pembayaran",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["id_pelanggan", "produk", "jenis_pengiriman"],
                            "properties": {
                                "id_pelanggan": {
                                    "type": "string",
                                    "example": "PEL001"
                                },
                                "produk": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": ["id_produk", "jumlah"],
                                        "properties": {
                                            "id_produk": {"type": "string"},
                                            "jumlah": {"type": "integer", "minimum": 1}
                                        }
                                    }
                                },
                                "jenis_pengiriman": {
                                    "type": "string",
                                    "enum": ["motor", "mobil", "ambil_sendiri"],
                                    "example": "motor"
                                },
                                "nama_driver": {
                                    "type": "string",
                                    "description": "Required untuk motor/mobil",
                                    "example": "Driver Name"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pembayaran berhasil dibuat",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"},
                                "data": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/pembayaran/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil data pembayaran berdasarkan ID",
                "produces": ["application/json"],
                "tags": ["Pembayaran"],
                "summary": "Get payment by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Payment ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data pembayaran berhasil diambil",
                        "schema": {"$ref": "#/definitions/models.Pembayaran"}
                    }
                }
            }
        },
        "/pembayaran/selesaikan/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Menyelesaikan transaksi pembayaran",
                "produces": ["application/json"],
                "tags": ["Pembayaran"],
                "summary": "Complete payment transaction",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Payment ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaksi berhasil diselesaikan",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {"type": "string"}
                            }
                        }
                    }
                }
            }
        },
        "/pembayaran/cetak/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Cetak surat jalan/struk pembayaran",
                "produces": ["application/pdf", "text/html"],
                "tags": ["Pembayaran"],
                "summary": "Print payment receipt",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Payment ID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File struk berhasil dibuat",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/riwayat": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil riwayat pembayaran berdasarkan role user",
                "produces": ["application/json"],
                "tags": ["Riwayat"],
                "summary": "Get payment history",
                "responses": {
                    "200": {
                        "description": "Riwayat pembayaran berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Pembayaran"}
                        }
                    }
                }
            }
        },
        "/users/drivers": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Mengambil semua data driver",
                "produces": ["application/json"],
                "tags": ["Driver"],
                "summary": "Get all drivers",
                "responses": {
                    "200": {
                        "description": "Data driver berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.User"}
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.User": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "DRV007"
                },
                "nama": {
                    "type": "string",
                    "example": "driver2"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "driver2@gmail.com"
                },
                "password": {
                    "type": "string",
                    "description": "Hashed password"
                },
                "role": {
                    "type": "string",
                    "enum": ["admin", "kasir", "driver"],
                    "example": "driver"
                },
                "no_hp": {
                    "type": "string",
                    "example": "083149869096"
                },
                "alamat": {
                    "type": "string",
                    "example": "Jln.rancabentang \\ rumah pak bombom"
                },
                "status": {
                    "type": "string",
                    "enum": ["aktif", "nonaktif"],
                    "example": "nonaktif"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-07-20T03:50:33.040+00:00"
                }
            }
        },
        "models.Produk": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "PRD001"
                },
                "nama_produk": {
                    "type": "string",
                    "example": "Produk A"
                },
                "kategori": {
                    "type": "string",
                    "example": "Kategori 1"
                },
                "harga": {
                    "type": "integer",
                    "example": 50000
                },
                "stok": {
                    "type": "integer",
                    "example": 100
                },
                "deskripsi": {
                    "type": "string",
                    "example": "Deskripsi produk"
                }
            }
        },
        "models.Pelanggan": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "PEL001"
                },
                "nama": {
                    "type": "string",
                    "example": "Jane Doe"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "jane@email.com"
                },
                "no_hp": {
                    "type": "string",
                    "example": "08123456789"
                },
                "alamat": {
                    "type": "string",
                    "example": "Jl. Contoh No. 123"
                }
            }
        },
        "models.Pembayaran": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "TRX001"
                },
                "id_pelanggan": {
                    "type": "string",
                    "example": "PEL001"
                },
                "nama_pelanggan": {
                    "type": "string",
                    "example": "Jane Doe"
                },
                "id_kasir": {
                    "type": "string",
                    "example": "USR002"
                },
                "nama_kasir": {
                    "type": "string",
                    "example": "Kasir Name"
                },
                "id_driver": {
                    "type": "string",
                    "example": "USR003"
                },
                "nama_driver": {
                    "type": "string",
                    "example": "Driver Name"
                },
                "jenis_pengiriman": {
                    "type": "string",
                    "enum": ["motor", "mobil", "ambil_sendiri"],
                    "example": "motor"
                },
                "produk": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id_produk": {"type": "string"},
                            "nama_produk": {"type": "string"},
                            "harga": {"type": "integer"},
                            "jumlah": {"type": "integer"},
                            "subtotal": {"type": "integer"}
                        }
                    }
                },
                "total_bayar": {
                    "type": "integer",
                    "example": 70000
                },
                "ongkir": {
                    "type": "integer",
                    "example": 10000
                },
                "tanggal": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "enum": ["Pending", "Selesai"],
                    "example": "Pending"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:5000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Backend MBG API",
	Description: "API documentation untuk Backend MBG application.\n\n**Sistem Login:**\n- Admin: admin@email.com / password123\n- Kasir: kasir@email.com / password123\n- Driver: driver@email.com / password123\n\n**Authentication:**\n- Semua endpoint (kecuali login) memerlukan Bearer Token\n- Token didapat dari endpoint /auth/login\n- Format: Authorization: Bearer {token}\n\n**Role Permissions:**\n- Admin: Akses penuh ke semua fitur\n- Kasir: CRUD produk, pelanggan, pembayaran, lihat riwayat\n- Driver: Lihat pembayaran assigned, update status selesai, cetak surat jalan",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register("swagger", &s{})
}
